.\" roar_simple_play.3:

.TH "roar_simple_connect" "3" "July 2008" "RoarAudio" "System Manager's Manual: RoarAuido"

.SH NAME
roar_simple_connect \- Opens a connection to RoarAudio's sound server

.SH SYNOPSIS

#include <roaraudio.h>

int roar_simple_connect (struct roar_connection * con, char * server, char * name);

.SH "DESCRIPTION"
This call opens a connection to the RoarAudio's sound server. This is usefull for controlling the server or
update meta data of any kind. For simple playback see \fBroar_simple_play\fR(3).
To disconnect use \fBroar_disconnect\fR(3).

.SH "PARAMETERS"
.TP
\fBcon\fR
The roar_connection object to be filled on success with all data needed for comunicating with the server.
This is used by nearly all other functions.

.TP
\fBserver\fR
The host or filename of the socket of the server. Should normaly be \fBNULL\fR to try default locations.

.TP
\fBname\fR
The name of this client. Should be the name of the player without any paths or filenames.

.SH "RETURN VALUE"
On success these calls return 0.  On error, -1 is returned.

.SH "EXAMPLES"
FIXME

.SH "SEE ALSO"
\fBroar_disconnect\fR(3),
\fBroar_simple_play\fR(3),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.\" ll
