.\" RoarAudio
.TH "roartips" "7" "August 2008" "RoarAudio" "System Manager's Manual: RoarAuido"

.SH NAME
roartips \- Tips for RoarAudio users

.SH SYNOPSIS


.SH "DESCRIPTION"

.SH "SEE ALSO"
\fBroarcat\fR(1),
\fBroarctl\fR(1),
\fBroarfilt\fR(1),
\fBroarfish\fR(1),
\fBroarmon\fR(1),
\fBroarvorbis\fR(1),
\fBroard\fR(1),
\fBlibroar\fR(7).

.\"ll
