.\" RoarAudio
.TH "RoarAudio" "7" "July 2008" "RoarAudio" "System Manager's Manual: RoarAuido"

.SH NAME
RoarAudio \- RoarAudio sound system

.SH SYNOPSIS

\fBroard\fR [OPTIONS]...

.SH "DESCRIPTION"
\fBRoarAudio\fR is a network transparent sound system like good old EsounD but supports some more features.

.SH "MAIN FEATURES"
 * multible audio streams per client
 * synchronized audio streams
 * vorbis comments like meta data for each audio stream
 * support for EsounD clients via libroaresd
 * mixing clients at individuell levels like an analog mixer
 * and many more...

.SH "BUGS"
A lot...

.SH "SEE ALSO"
\fBroar-config\fR(1),
\fBroarcat\fR(1),
\fBroarcat2sock\fR(1),
\fBroarcatad\fR(1),
\fBroarctl\fR(1),
\fBroarfilt\fR(1),
\fBroarfish\fR(1),
\fBroarmon\fR(1),
\fBroarsockconnect\fR(1),
\fBroartypes\fR(1),
\fBroarvorbis\fR(1),
\fBroard\fR(1),
\fBlibroar\fR(7).

.SH "HISTORY"
Project started in mid of 2008.

.\"ll
