.\" roarsocktypes.1:

.TH "roarsocktypes" "1" "January 2010" "RoarAudio" "System User's Manual: roarsocktypes"

.SH NAME

roarsocktypes \- List socket types supported by RoarAudio

.SH SYNOPSIS

roarsocktypes

.SH DESCRIPTION

List socket types that are supported and test them at runtime.

.SH "SEE ALSO"
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
