.\" roartypes.1:

.TH "roartypes" "1" "January 2010" "RoarAudio" "System User's Manual: roartypes"

.SH NAME

roartypes \- List sizes of well known RoarAudio C types

.SH SYNOPSIS

roartypes

.SH DESCRIPTION

List sizes of well known RoarAudio C types.

.SH "SEE ALSO"
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
