.\" roarvorbis.1:

.TH "roarvorbis" "1" "January 2010" "RoarAudio" "System User's Manual: roarvorbis"

.SH NAME

roarvorbis \- Ogg Vorbis player for RoarAudio

.SH SYNOPSIS

roarvorbis [OPTIONS]... FILE

.SH DESCRIPTION

Plays an Ogg Vorbis file showing it's metadata.

.SH "OPTIONS"

.TP
\fB--server SERVER\fR
Set server hostname

.TP
\fB--help\fR
Show this help

.TP
\fB--vclt-out FILE\fR
Writes VCLT file

.SH "SEE ALSO"
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
