.\" roarfish.1:

.TH "roarfish" "1" "January 2010" "RoarAudio" "System User's Manual: roarfish"

.SH NAME

roarfish \- operate on fishsound files

.SH SYNOPSIS

roarfish COMMAND FILE [OPTIONS]

.SH DESCRIPTION

This program can operate on files using libfishsound.

.SH "COMMANDS"

.TP
\fBplay FILE\fR
plays a file

.SH "SEE ALSO"
\fBroarcatplay\fR(1),
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
