.\" roarmonhttp.1:

.TH "roarmonhttp" "1" "January 2010" "RoarAudio" "System User's Manual: roarmonhttp"

.SH NAME

roarmonhttp \- CGI and inetd based streaming server emulation for RoarAudio

.SH SYNOPSIS

roarmonhttp [\-\-inetd]

.SH DESCRIPTION

This program emulates a streaming server using RoarAudio.
It can be run from via a webserver as CGI or via inetd in inetd mode.
IN CGI mode it is limited to client (listener) HTTP connections.
In inetd mode it can handle source clients and gopher, too.
There is no need for a specal port for gopher. The protocol
is detected per client at runtime.

.SH "OPTIONS"

.TP
\fB--inetd\fR
Enables inetd mode.

.TP
\fB--server SERVER\fR
Set Server to connect to. This may be usfull in inetd mode.

.TP
\fB--rate\fR, \fB--bits\fR, \fB--channels\fR, \fB--codec\fR
Sets the default rate, bits, channels or codec.
Those option taking a argument for the given option. Codec names may be used.

.TP
\fB--rel-id SID\fR
Set the stream ID for the stream this stream is relative to.

.TP
\fB--help\fR
Show a brief help.

.SH "EXAMPLES"
Here is an example of a roarmonhttp listening on port 8000 using inetd:
 8000 stream tcp nowait roard /usr/bin/roarmonhttp roarmonhttp \-\-inetd

.SH "SEE ALSO"
\fBinetd\fR(8),
\fBinetd.conf\fR(5),
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
