.\" roarfctest.1:

.TH "roarfctest" "1" "July 2010" "RoarAudio" "System User's Manual: roarfctest"

.SH NAME

roarfctest \- Test frequency behavior of filters in discrete time domain

.SH SYNOPSIS

roarfctest [OPTIONS]...

.SH DESCRIPTION

This program tests libroardsp filters in discrete time domain.

.SH "OPTIONS"

.TP
\fB--rate      RATE\fR
Set sample rate

.TP
\fB--sfreq     SFREQ\fR
Start frequency

.TP
\fB--efreq     EFREQ\fR
End frequency

.TP
\fB--engage    ENGAGE\fR
This option is not documented

.TP
\fB--tmax      TMAX\fR
This option is not documented

.TP
\fB--gnuplot\fR
Output data using gnuplot(1)

.TP
\fB--rmsout    RMSOUT\fR
Set output file for RMS data

.TP
\fB--help   \-h\fR
Show this help


.SH "SEE ALSO"
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
