.\" roarcatplay.1:

.TH "roarcatplay" "1" "January 2010" "RoarAudio" "System User's Manual: roarcatplay"

.SH NAME

roarcatplay \- play files via RoarAudio

.SH SYNOPSIS

roarcatplay [OPTIONS]... [FILE]

.SH DESCRIPTION

This tool plays files using RoarAudio doing client side auto detecting of file type.

.SH "OPTIONS"

.TP
\fB--server SERVER\fR
Set server hostname

.TP
\fB--simple\fR
Use the simple interface (default)

.TP
\fB--passive\fR
Use passiv playback (experimental, works only localy)

.TP
\fB--background\fR
Use background playback, impleys passive mode

.TP
\fB--verbose\fR
Use verbose output

.TP
\fB--help\fR
Show this help

.SH "SEE ALSO"
\fBroarcat\fR(1),
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
