.\" roard.1:

.TH "roarify" "1" "April 2009" "RoarAudio" "User Commands"

.SH NAME

roarify \- roarify an application that does not have RoarAudio support

.SH SYNOPSIS

roarify PROGRAM [ARGS...]

.SH "DESCRIPTION"
This command sets up a enviroment that enables all RoarAudio compatibility librarys.
Audio data from applications should automaticly be redirected to roard. 

.SH "SEE ALSO"
\fBroarctl\fR(1),
\fBroarcat\fR(1),
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
