.\" roarcatsendfile.1:

.TH "roarcatsendfile" "1" "July 2010" "RoarAudio" "System User's Manual: roarcatsendfile"

.SH NAME

roarcatsendfile \- Send audio data to RoarAudio sound server using old kernel land sendfile

.SH SYNOPSIS

roarcatsendfile [OPTIONS]... [FILE]

.SH DESCRIPTION

Send audio data to RoarAudio sound server using old kernel land sendfile.

.SH "OPTIONS"

.TP
\fB--server SERVER\fR
Set server hostname

.TP
\fB--rate   RATE\fR
Set sample rate

.TP
\fB--bits   BITS\fR
Set bits per sample

.TP
\fB--chans  CHANNELS\fR
Set number of channels

.TP
\fB--codec  CODEC\fR
Set the codec

.TP
\fB--help\fR
Show this help

.SH "SEE ALSO"
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
