.\" roar-config.1:

.TH "roar-config" "1" "January 2010" "RoarAudio" "System User's Manual: roar-config"

.SH NAME

roar-config \- get information of installed RoarAudio librarys

.SH SYNOPSIS

roar-config [\-\-version] [\-\-libs] [\-\-cflags] [lib]

.SH DESCRIPTION

This small tool prints information about installed versions and needed flags to work
with the RoarAudio librarys.

.SH "OPTIONS"

.TP
\fB--version\fR
Show version of library

.TP
\fB--libs\fR
Show linker flags (\-lxxx) needed to link library

.TP
\fB--cflags\fR
Show compiler flags needed to link library

.SH "SEE ALSO"
\fBroartips\fR(7),
\fBlibroar\fR(7),
\fBRoarAudio\fR(7).

.SH "HISTORY"

For history information see \fBRoarAudio\fR(7).

.\" ll
